name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10-alpine

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Chekout
        uses: actions/checkout@v2

      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt

      - name: Create conda environment and install numpy
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a

          conda create -n numpy_env python=3.8 numpy pandas
          conda activate numpy_env

      - name: Run unit tests with pytest
        run: pytest

      - name: Lint with flake8
        run: flake8 --filename=*.py app/
